version: '3.3'
services:
  rabbitmq:
    image: rabbitmq
    networks:
      - backend
    ports:
      - "5672:5672"
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - backend
    ports:
      - "5432:5432"
  listener:
    build:
      context: ./listener
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - database
    links:
      - rabbitmq
      - database
    networks:
      - backend
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - backend
    tty: true
    stdin_open: true

networks:
  backend:
